service:
  name: Achieveit

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
#  port: 8443
#  ssl:
#    enabled: true
#    key-store: classpath:rainkq.tk.pfx
#    key-store-password: 9PYuKznP
#    key-store-type: PKCS12

#http-port: 8080


#redis信息
redis:
  host: rainkqrainkq.redis.rds.aliyuncs.com
  port: 6379
  password: achieveit:Achieve1t

#mail
spring:
  mail:
#    host: smtp.exmail.qq.com
    #    username: achieveit@rainkq.tk
    # 授权码
    #    password: D62ie83pa62uHp9Y
    host: smtp.qq.com
    username: 1071754083@qq.com
    password: jmyncyfnxumfbfac

    properties:
      mail:
        default-encoding: UTF-8
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  cache:
    redis:
      time-to-live: 600000


  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
